# NumPy 

NumPy는 파이썬용으로 강력한 선형대수 라이브러리입니다. 중요하게 여겨지는 이유 중 하나는 PyData 생태계(<a href='https://pydata.org/'>pandas, scipy, scikit-learn</a> 등)의 거의 모든 라이브러리가 NumPy를 주요 빌딩 블록으로 사용한다는 점입니다. 또한 이후의 분석 예제에서 데이터를 생성할 때 NumPy를 사용할 것입니다!

NumPy는 C 라이브러리에 대한 바인딩을 사용하기 때문에 매우 빠릅니다. 리스트 대신 배열을 사용해야 하는 이유에 대한 자세한 내용은 이 훌륭한 [StackOverflow 포스트](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists)를 참고하세요.

여기서는 NumPy의 기초만 다룹니다. 시작하려면 먼저 설치가 필요합니다!

## 설치 안내

### NumPy는 이미 제공된 환경에 포함되어 있습니다! `tsa_course` 환경을 사용 중이라면 바로 사용하실 수 있습니다!

_____
##### 제공된 환경을 사용하지 않는 분들을 위해:

**Anaconda 배포판을 사용해 Python을 설치하는 것을 강력히 권장합니다. 이렇게 하면 선형대수 라이브러리와 같은 기본 종속성이 conda 설치와 함께 잘 동작합니다. Anaconda가 설치되어 있다면 터미널(또는 명령 프롬프트)에서 다음을 입력하여 NumPy를 설치하세요:**

    conda install numpy
    
**Anaconda가 없고 설치할 수 없는 경우, 다양한 설치 방법에 대해서는 [Numpy 공식 설치 문서](https://www.scipy.org/install.html)를 참조하세요.**

_____

## NumPy 사용하기

NumPy를 설치한 후에는 다음처럼 라이브러리로 불러올 수 있습니다:

In [1]:
import numpy as np

NumPy에는 많은 내장 함수와 기능이 있습니다. 모두 다루지는 않겠지만, 여기서는 NumPy에서 특히 중요한 몇 가지 주제: 벡터, 배열, 행렬, 그리고 숫자 생성 등을 중심으로 설명하겠습니다. 먼저 배열부터 시작하겠습니다.

# NumPy 배열

NumPy 배열은 이 강의 전반에서 NumPy를 사용하는 주요 방식입니다. NumPy 배열에는 크게 두 가지 형태가 있습니다: 벡터와 행렬입니다. 벡터는 엄격히 1차원(1D) 배열이고, 행렬은 2차원(2D)입니다(단, 행렬은 한 행 또는 한 열만 가질 수 있습니다).

이제 NumPy 배열을 만드는 방법을 살펴보면서 소개를 시작하겠습니다.

## NumPy 배열 생성

### 파이썬 리스트에서

리스트 또는 리스트의 리스트를 바로 변환하여 배열을 만들 수 있습니다:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 내장 메서드

배열을 생성하는 여러 가지 내장 기능이 있습니다.

### arange

주어진 구간 내에서 균등한 간격의 값을 반환합니다. [[참고](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros와 ones

0 또는 1로 채워진 배열을 생성합니다. [[참고](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.ones((5,5)) + 5

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [21]:
np.ones(4) / 100

array([0.01, 0.01, 0.01, 0.01])

### linspace 
지정된 구간에 걸쳐 균등한 간격으로 숫자를 반환합니다. [[참고](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

<font color=green>`.linspace()`는 종료값을 포함합니다. 일반적인 분수를 얻으려면 항목 수를 늘리세요:</font>

In [15]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [17]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

### eye

단위 행렬(identity matrix)을 생성합니다. [[참고](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## 난수
NumPy에는 난수 배열을 생성하는 여러 방법이 있습니다:

### rand
지정한 형태의 배열을 만들고 균등 분포 [0, 1)에서 샘플로 채웁니다. [[참고](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [23]:
np.random.rand(2)

array([0.00255873, 0.23027673])

In [24]:
np.random.rand(5,5)

array([[0.92440022, 0.85678491, 0.30661746, 0.65190905, 0.91218567],
       [0.103042  , 0.50650973, 0.95927479, 0.65012234, 0.87792026],
       [0.4106999 , 0.0367569 , 0.72527115, 0.33326677, 0.80004086],
       [0.44268422, 0.3044672 , 0.58280506, 0.49321632, 0.77751625],
       [0.1084891 , 0.54818909, 0.51152314, 0.13069781, 0.78860238]])

In [25]:
np.random.randint(1, 45, size=6)

array([23, 37, 17, 28, 35,  8], dtype=int32)

### randn

표준 정규 분포(σ = 1)에서 샘플(또는 샘플들)을 반환합니다. **rand**가 균등 분포인 것과 달리, 0에 가까운 값이 더 자주 나타납니다. [[참고](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]

In [26]:
np.random.randn(2)

array([-0.53179427,  0.68157347])

In [27]:
np.random.randn(5, 5)

array([[ 0.8695756 ,  1.02089774,  0.754512  ,  0.22775727,  1.01718745],
       [-0.27062241, -0.00748869, -0.54212073, -0.75797528, -1.40822352],
       [ 0.34795955, -0.2385974 , -0.65479849,  0.57342627, -1.13365801],
       [ 0.96133626, -0.82800938,  0.80939506,  0.26044463, -0.89421038],
       [ 0.49137083, -0.35797369, -0.30303251,  0.75443556, -2.05916885]])

### randint

`low`(포함)에서 `high`(미포함) 사이의 정수를 무작위로 반환합니다.  [[참고](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [28]:
np.random.randint(1,100)

7

In [29]:
np.random.randint(1,100,10)

array([42, 36, 94, 83, 61, 31, 87, 99, 80, 76], dtype=int32)

### seed

난수 상태를 설정하여 동일한 '무작위' 결과를 재현할 수 있습니다. [[참고](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [30]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## 배열 속성 및 메서드

배열에서 자주 쓰이는 유용한 속성과 메서드를 살펴보겠습니다:

In [32]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2], dtype=int32)

In [35]:
ranarr.max()

np.int32(39)

In [36]:
ranarr.min()

np.int32(2)

In [ ]:
ranarr.argmax() # index of max value

np.int64(7)

In [38]:
ranarr.argmin() # index of min value

np.int64(9)

## Reshape

같은 데이터를 가지면서 새로운 모양의 배열을 반환합니다. [[참고](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

이 메서드들은 최댓값이나 최솟값을 찾을 때 유용합니다. 또한 argmin이나 argmax를 사용하면 해당 값들의 인덱스 위치를 알 수 있습니다.

In [28]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [29]:
ranarr.max()

39

In [30]:
ranarr.argmax()

7

In [31]:
ranarr.min()

2

In [32]:
ranarr.argmin()

9

## Shape

shape는 배열이 가지는 속성(메서드가 아님)입니다:  [[참고](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [33]:
# Vector
arr.shape

(25,)

In [34]:
# 대괄호 두 쌍에 주의하세요
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(1,25).shape

(1, 25)

In [36]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [37]:
arr.reshape(25,1).shape

(25, 1)

### dtype

배열 요소의 데이터 타입도 확인할 수 있습니다: [[참고](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [38]:
arr.dtype

dtype('int32')

In [39]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

# 잘하셨어요!
