# NumPy 인덱싱 및 선택

이번 강의에서는 배열에서 요소 또는 요소 그룹을 선택하는 방법을 다룹니다.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 대괄호 인덱싱과 선택
배열의 하나 또는 일부 요소를 선택하는 가장 간단한 방법은 파이썬 리스트와 매우 유사합니다:

In [4]:
#Get a value at an index
arr[8]

np.int64(8)

In [5]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [6]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## 브로드캐스팅

NumPy 배열은 브로드캐스팅 기능 때문에 일반 파이썬 리스트와 다릅니다. 리스트에서는 같은 크기와 형태의 새로운 부분으로만 일부를 재할당할 수 있습니다. 예를 들어 리스트의 처음 5개 요소를 새 값으로 바꾸려면 새로운 5개짜리 리스트를 넘겨야 합니다. NumPy 배열에서는 단일 값을 더 큰 값 집합에 브로드캐스트(확장)할 수 있습니다:

In [10]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

이제 변경사항이 원본 배열에도 반영되는 것을 확인하세요!

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

데이터가 복사되는 것이 아니라 원본 배열의 뷰(view)입니다! 이로 인해 메모리 문제를 피할 수 있습니다!

In [15]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## 2차원 배열(행렬) 인덱싱

일반 형식은 **arr_2d[row][col]** 또는 **arr_2d[row,col]** 입니다. 명확성을 위해 쉼표 표기법을 사용하는 것을 권장합니다.

In [16]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [18]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

np.int64(20)

In [19]:
# Getting individual element value
arr_2d[1,0]

np.int64(20)

In [20]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [21]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [22]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [23]:
arr_2d.shape

(3, 3)

## 인덱싱 도움말 추가
2차원 행렬의 인덱싱은 처음에 다소 혼란스러울 수 있습니다. 특히 슬라이스의 스텝(step)을 추가하면 더 그렇습니다. 유용한 이미지를 찾으려면 Google 이미지에서 *NumPy indexing*을 검색해 보세요. 예:

<img src= 'numpy_indexing.png' width=500/> 이미지 출처: http://www.scipy-lectures.org/intro/numpy/numpy.html

## 조건부 선택

이는 나중에 pandas로 바로 이어지는 매우 기본적인 개념이므로 반드시 이해하세요!

이제 비교 연산자를 기반으로 대괄호를 사용하여 선택하는 방법을 간단히 살펴보겠습니다.

In [24]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [26]:
bool_arr = arr>4

In [27]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr] # True인 값만 가져오기

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2] # 2보다 큰 값만 가져오기

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])