# NumPy 연산

## 산술 연산

배열 간 연산이나 스칼라와 배열 간의 연산을 쉽게 수행할 수 있습니다. 몇 가지 예시를 보겠습니다:

In [1]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# This will raise a Warning on division by zero, but not an error!
# It just fills the spot with nan
arr/arr

C:\Anaconda3\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
# Also a warning (but not an error) relating to infinity
1/arr

C:\Anaconda3\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [7]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## 유니버설 배열 함수(ufunc)

NumPy는 많은 유니버설 배열 함수(ufunc)를 제공합니다. 이는 배열 전체에 적용할 수 있는 수학적 연산들입니다.<br>몇 가지 일반적인 예를 보여드리겠습니다:

In [8]:
# Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [9]:
# Calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [10]:
# Trigonometric Functions like sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [11]:
# Taking the Natural Logarithm
np.log(arr)

C:\Anaconda3\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## 배열에 대한 요약 통계

NumPy는 합계(<em>sum</em>), 평균(<em>mean</em>), 최댓값(<em>max</em>)과 같은 일반적인 요약 통계 함수를 제공합니다. 이러한 함수들은 배열의 메서드로 호출합니다.

In [12]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr.sum()

45

In [14]:
arr.mean()

4.5

In [15]:
arr.max()

9

<strong>다른 요약 통계 예:</strong>
<pre>
arr.min() returns 0                   최소값
arr.var() returns 8.25                분산
arr.std() returns 2.8722813232690143  표준편차
</pre>

## 축(axis) 논리
2차원 배열(행렬)을 다룰 때는 행과 열을 고려해야 합니다. 이는 나중에 pandas 섹션에서 매우 중요합니다. 배열 관점에서 axis 0은 세로 축(행), axis 1은 가로 축(열)을 의미합니다. 이 값들(0,1)은 <tt>arr.shape</tt>이 반환되는 순서를 나타냅니다.

이것이 위의 요약 통계 계산에 어떻게 영향을 주는지 보겠습니다.

In [16]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

<tt>axis=0</tt>을 전달하면 세로 축을 따라 합계를 계산한 배열을 반환합니다. 즉 <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>입니다.

<img src='axis_logic.png' width=400/>

In [18]:
arr_2d.shape

(3, 4)

이는 <tt>arr_2d</tt>가 3행 4열임을 알려줍니다.

위의 <tt>arr_2d.sum(axis=0)</tt>에서는 각 행의 첫 번째 요소들끼리 합해지고, 그 다음 두 번째 요소들끼리 합해지는 방식입니다.

그러면 <tt>arr_2d.sum(axis=1)</tt>은 무엇을 반환해야 할까요?

In [ ]:
# THINK ABOUT WHAT THIS WILL RETURN BEFORE RUNNING THE CELL!
arr_2d.sum(axis=1)

# 잘하셨어요!

지금은 이 정도만 알아도 충분합니다!