___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>저작권 Pierian Data</em></center>
<center><em>자세한 정보는 <a href='http://www.pieriandata.com'>www.pieriandata.com</a>을 방문하세요</em></center>

# NumPy 연습문제 - 해답

이제 NumPy를 배웠으니 지식을 테스트해봅시다. 먼저 몇 가지 간단한 문제부터 시작한 후 더 복잡한 문제로 진행합니다.

<div class="alert alert-danger" style="margin: 10px"><strong>중요!</strong> 아래에 표시된 예시 출력 바로 위의 셀을 실행하지 마세요. 그렇지 않으면 예시 출력이 덮어써집니다!</div>

#### 1. `NumPy`를 `np`로 임포트하세요

In [1]:
import numpy as np

#### 2. 10개의 0으로 이루어진 배열을 만드세요

In [ ]:
# CODE HERE


In [2]:
# DON'T WRITE HERE
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. 10개의 1로 이루어진 배열을 만드세요

In [3]:
# DON'T WRITE HERE
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. 10개의 5로 이루어진 배열을 만드세요

In [4]:
# DON'T WRITE HERE
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. 10부터 50까지의 정수로 이루어진 배열을 만드세요

In [5]:
# DON'T WRITE HERE
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. 10부터 50까지의 모든 짝수 정수로 이루어진 배열을 만드세요

In [6]:
# DON'T WRITE HERE
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. 값이 0부터 8까지인 3x3 행렬을 만드세요

In [7]:
# DON'T WRITE HERE
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. 3x3 항등행렬을 만드세요

In [8]:
# DON'T WRITE HERE
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. NumPy를 사용하여 0과 1 사이의 난수를 생성하세요<br><br>&emsp;참고: 실행 결과는 아래 예시값과 달라야 합니다.

In [9]:
# DON'T WRITE HERE
np.random.rand(1)

array([0.65248055])

#### 10. 표준 정규분포에서 샘플링한 25개의 난수 배열을 NumPy로 생성하세요<br><br>&emsp;&ensp;참고: 결과 값은 아래 예시와 달라야 합니다.

In [10]:
# DON'T WRITE HERE
np.random.randn(25)

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 11. 다음 행렬을 만드세요:

In [11]:
# DON'T WRITE HERE
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. 0과 1 사이를 선형 간격으로 나눈 20개의 점으로 이루어진 배열을 만드세요:

In [12]:
# DON'T WRITE HERE
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## NumPy 인덱싱 및 선택

이제 시작 행렬이 제공됩니다(아래 셀을 꼭 실행하세요!). 이후에 나타나는 결과 행렬을 재현하는 코드를 작성하세요:

In [13]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. 아래에 표시된 출력을 재현하는 코드를 작성하세요.<br><br>&emsp;&ensp;바로 위의 셀을 실행하면 출력이 사라지므로 주의하세요.

In [ ]:
# CODE HERE


In [14]:
# DON'T WRITE HERE
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. 아래에 표시된 출력을 재현하는 코드를 작성하세요.

In [15]:
# DON'T WRITE HERE
mat[3,4]

20

#### 15. 아래에 표시된 출력을 재현하는 코드를 작성하세요.

In [16]:
# DON'T WRITE HERE
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

#### 16. 아래에 표시된 출력을 재현하는 코드를 작성하세요.

In [17]:
# DON'T WRITE HERE
mat[4,:]

array([21, 22, 23, 24, 25])

#### 17. 아래에 표시된 출력을 재현하는 코드를 작성하세요.

In [18]:
# DON'T WRITE HERE
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## NumPy 연산

#### 18. `mat`의 모든 값의 합을 구하세요

In [19]:
# DON'T WRITE HERE
mat.sum()

325

#### 19. `mat` 값들의 표준편차를 구하세요

In [20]:
# DON'T WRITE HERE
mat.std()

7.211102550927978

#### 20. `mat`의 모든 열에 대한 합을 구하세요

In [21]:
# DON'T WRITE HERE
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

## 보너스 문제

NumPy로 난수를 많이 다뤘는데, 항상 동일한 난수를 얻도록 보장할 수 있는 방법이 있을까요? [힌트 보기](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)

In [ ]:
np.random.seed(101)

# 잘했어요!